apiVersion: v1
kind: Namespace
metadata:
  name: accounts
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-api
  namespace: accounts
spec:
  replicas: 1
  selector:
    matchLabels: { app: accounts-api }
  template:
    metadata:
      labels: { app: accounts-api }
    spec:
      containers:
        - name: accounts-api
          image: accounts-api:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3002"
            - name: IDENTITY_URL
              value: "http://identity-api.identity.svc.cluster.local:3001"
            - name: CATALOG_URL
              value: "http://catalog-api.catalog.svc.cluster.local:3003"
            # Insights (set by accounts orchestrator)
            # Get from Insights in Workspace
            - name: POSTMAN_INSIGHTS_PROJECT_ID
              value: "__ACCOUNTS_PROJECT_ID__"
            - name: POSTMAN_INSIGHTS_API_KEY
              value: "__POSTMAN_API_KEY__"
            # Get from API Catalog
            - name: POSTMAN_INSIGHTS_WORKSPACE_ID
              value: "__ACCOUNTS_WORKSPACE_ID__"
            - name: POSTMAN_INSIGHTS_SYSTEM_ENV
              value: "__POSTMAN_SYSTEM_ENV__"
          ports:
            - containerPort: 3002
          readinessProbe:
            httpGet: { path: /health, port: 3002 }
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /health, port: 3002 }
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-api
  namespace: accounts
spec:
  selector: { app: accounts-api }
  ports:
    - name: http
      port: 3002
      targetPort: 3002
