apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
  namespace: accounts
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /identity/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: identity-api
                port:
                  number: 3001
          - path: /accounts/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: accounts-api
                port:
                  number: 3002
          - path: /catalog/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: catalog-api
                port:
                  number: 3003
